In [ ]:
import pandas as pd
from statsmodels.stats.inter_rater import fleiss_kappa, aggregate_raters, cohens_kappa
import numpy as np

df = pd.read_csv('data/FMA_similarity_evaluation.xlsx - Evaluators_main16_joined.csv')

df.rename(columns={'Evaluator': 'annotator', 'Track_id': 'track_id'}, inplace=True)

# get rid of the "Main" similarity values

df_edited = df[df['Similarity'] != "Main"]


df_pivoted = df_edited.pivot_table(index=['track_id'], columns='annotator', values='Similarity', aggfunc='first')
# Reset the index to move 'track_id' from index to a column
df = df_pivoted.reset_index()
df.columns.name = None
df.drop(columns=['track_id'], inplace=True)
df.reset_index(drop=True, inplace=True)

df.rename(columns={1: 'annotator_1', 2: 'annotator_2', 3:'annotator_3'}, inplace=True)

df.head()

# Initialize an empty list to store counts for each track
contingency_table = []

ratings = ['D', 'N', 'VS','S']

# Iterate through each row (track) and count the occurrences of each rating
for _, row in df_pivoted.iterrows():
    track_ratings = row.values
    # Count the occurrences of each rating
    counts = [sum(track_ratings == rating) for rating in ratings]
    contingency_table.append(counts)

# Convert the contingency table to a numpy array
contingency_array = np.array(contingency_table)

print(contingency_array)

# Calculate Fleiss' Kappa
aggregate_raters(contingency_array, n_cat=4)

result = fleiss_kappa(contingency_array)

print(result)




[[2 0 0 1]
 [0 0 3 0]
 [2 0 0 1]
 [1 2 0 0]
 [2 1 0 0]
 [0 0 3 0]
 [0 0 3 0]
 [0 0 3 0]
 [0 0 3 0]
 [0 0 3 0]
 [0 0 3 0]
 [0 0 2 1]
 [0 0 3 0]
 [0 0 2 1]
 [0 2 0 1]
 [3 0 0 0]
 [0 0 3 0]
 [3 0 0 0]
 [2 0 0 1]
 [0 3 0 0]
 [1 1 0 1]
 [1 1 0 1]
 [1 0 0 2]
 [0 1 0 2]
 [0 3 0 0]
 [1 1 0 1]
 [1 0 0 2]
 [0 0 1 2]
 [1 0 0 2]
 [0 0 1 2]
 [0 0 1 2]
 [0 1 0 2]
 [0 0 1 2]
 [0 0 0 3]
 [1 0 0 2]
 [0 0 0 3]
 [0 0 3 0]
 [0 0 3 0]
 [0 0 3 0]
 [0 0 3 0]
 [0 0 2 1]
 [0 2 0 1]
 [0 0 0 3]
 [0 2 0 1]
 [0 0 1 2]
 [1 1 0 1]
 [1 2 0 0]
 [2 0 0 1]
 [1 1 0 1]
 [2 1 0 0]
 [1 0 0 2]
 [0 2 1 0]
 [0 0 3 0]
 [2 1 0 0]
 [0 0 2 1]
 [0 0 1 2]
 [0 0 3 0]
 [0 0 2 1]
 [2 1 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 3 0]
 [1 2 0 0]
 [0 0 3 0]
 [2 1 0 0]]
0.4154085097161021
